[package]
name = "clip-vault-proto"
version.workspace = true
authors.workspace = true
description = "IPC types shared between the daemon and clients."
edition.workspace = true
readme.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clip-vault-core = { path = "../clip-vault-core", version = "0.0.1" }
serde = { workspace = true }
serde_json = "1"
thiserror = { workspace = true }

[lints]
workspace = true
